# -*- coding=utf-8 -*-
r"""

"""
import typing as t
from ..color import Color


def register_generator(generator: t.Callable[[], Color]): ...


@t.overload
def generate() -> Color: ...
@t.overload
def generate(generator: t.Literal["basic", "no-mono", "colorful", "colorless"]) -> Color: ...
@t.overload
def generate(generator: str) -> Color: ...


def generate_basic() -> Color: ...
def generate_no_mono() -> Color: ...
def generate_colorful() -> Color: ...
def generate_colorless() -> Color: ...
